# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/angular-s.o.l.i.d-advanced"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # For API_s.o.l.i.d_TS
    directory: "/API_s.o.l.i.d_TS"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # For astro-starter
    directory: "/astro-starter"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # For nestjs-s.o.l.i.d
    directory: "/nestjs-s.o.l.i.d"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # For next-prisma-starter
    directory: "/next-prisma-starter"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # For nodejs-s.o.l.i.d
    directory: "/nodejs-s.o.l.i.d"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # For nuxt-clean-architecture
    directory: "/nuxt-clean-architecture"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # For react-s.o.l.i.d
    directory: "/react-s.o.l.i.d"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # For tauri-sveltekit
    directory: "/tauri-sveltekit"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # For vue.js-s.o.l.i.d
    directory: "/vue.js-s.o.l.i.d"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # For vue3-clean-architecture
    directory: "/vue3-clean-architecture"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "npm" # For vue3-clean-architecture
    directory: "/sveltekit"
    schedule:
      interval: "weekly"
  
 
