# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/angular-s.o.l.i.d-advanced" # Location of the package.json
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # For API_s.o.l.i.d_TS
    directory: "/API_s.o.l.i.d_TS" # Location of the package.json
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # For nestjs-s.o.l.i.d
    directory: "/nestjs-s.o.l.i.d" # Location of the package.json
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # For next-prisma-starter
    directory: "/next-prisma-starter" # Location of the package.json
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # For nodejs-s.o.l.i.d
    directory: "/nodejs-s.o.l.i.d" # Location of the package.json
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # For nodejs-s.o.l.i.d
    directory: "/nuxt-clean-architecture" # Location of the package.json
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # For react-s.o.l.i.d
    directory: "/react-s.o.l.i.d" # Location of the package.json
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # For vue.js-s.o.l.i.d
    directory: "/vue.js-s.o.l.i.d" # Location of the package.json
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # For vue3-clean-architecture
    directory: "/vue3-clean-architecture" # Location of the package.json
    schedule:
      interval: "weekly"