# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
  directory: "/angular-s.o.l.i.d-advanced"
  schedule:
    interval: "weekly"

- package-ecosystem: "npm"
  directory: "/API_s.o.l.i.d_TS"
  schedule:
    interval: "weekly"

- package-ecosystem: "npm"
  directory: "/nestjs-s.o.l.i.d"
  schedule:
    interval: "weekly"

- package-ecosystem: "npm"
  directory: "/next-prisma-starter"
  schedule:
    interval: "weekly"

- package-ecosystem: "npm"
  directory: "/nodejs-s.o.l.i.d"
  schedule:
    interval: "weekly"

- package-ecosystem: "npm"
  directory: "/react-s.o.l.i.d"
  schedule:
    interval: "weekly"

- package-ecosystem: "npm"
  directory: "/vue.js-s.o.l.i.d"
  schedule:
    interval: "weekly"

- package-ecosystem: "npm"
  directory: "/vue3-clean-architecture"
  schedule:
    interval: "weekly"
    schedule:
      interval: "weekly"

