[tool.poetry]
name = "frontend"
version = "0.1.0"
description = ""
authors = ["ssgrummons <ssgrummo@us.ibm.com>"]
readme = "README.md"
package-mode = false 

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
streamlit = "^1.62.0"
python-dotenv = "^1.2.3"
aiohttp = "^3.14.3"

[tool.poetry.group.dev.dependencies]
pytest = "^9.1.1"
pytest-mock = "^3.15.1"
pytest-cov = "^7.1.0"  # Optional, for coverage reporting

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
