services:
  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile
      args:
        EMBEDDING_MODEL: ${EMBEDDING_MODEL}
    ports:
      - "8000:8000"
    depends_on:
      milvus-standalone:
        condition: service_healthy
    env_file:
      - ../backend/src/.env
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 240s
      retries: 10

  frontend:
    build: 
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - ../frontend/src/.env
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

  attu:
    image: zilliz/attu:v2.5
    ports:
      - "8088:3000"
    environment:
      - MILVUS_URL=milvus-standalone:19530
    depends_on:
      milvus-standalone:
        condition: service_healthy
    networks:
      - app-network

  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - ./vols/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./vols/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - app-network

  milvus-standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.5.6
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ./milvus.yaml:/milvus/configs/milvus.yaml
      - ./vols/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
    depends_on:
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  milvus-data:
  milvus-etcd-data:
  milvus-minio-data:
